fix workflows

diff --git a/workflows/spyglass-apply-dry-run.yml b/workflows/spyglass-apply-dry-run.yml
--- a/workflows/spyglass-apply-dry-run.yml
+++ b/workflows/spyglass-apply-dry-run.yml
@@ -28,7 +28,17 @@ jobs:
         run: |
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           echo "COMMENT_BODY<<$EOF" >> $GITHUB_ENV
-          spyglass apply YOUR_ACCOUNT_ID_HERE --git-ref '${{ github.event.pull_request.base.sha }}' --dir YOUR_SPYGLASS_DIR_HERE --dry-run --markdown >> $GITHUB_ENV
+
+          set +e
+          spyglass apply YOUR_ACCOUNT_ID_HERE --git-ref '${{ github.event.pull_request.base.sha }}' --dir YOUR_SPYGLASS_DIR_HERE --dry-run --markdown >stdout.log 2>stderr.log
+          if [ $? -eq 0 ]; then
+            cat stdout.log >>$GITHUB_ENV
+          else
+            echo -e 'Spyglass dry run failed:\n' >>$GITHUB_ENV
+            cat stderr.log >>$GITHUB_ENV
+          fi
+          set -e
+
           echo "$EOF" >> $GITHUB_ENV
         env:
           SNOWSQL_CONFIG: ${{ secrets.SNOWSQL_CONFIG }}
@@ -44,3 +54,7 @@ jobs:
               repo: context.repo.repo,
               body: process.env.COMMENT_BODY
             })
+
+      - name: Check failure
+        if: steps.apply-dry-run.outcome != 'success'
+        run: exit 1
